### ISSUE TITLE
Error when trying to download

### ISSUE THREAD

**Issue by ghost** [shubham418/yiff_scraper#4]
When i try to download something, i have the following error:
```
*Starting project 17913091
Downloading 84059FEB-8E1A-4774-B16C-137F91797355.jpeg                                                                   Traceback (most recent call last):
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection                                                                                                          for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000021C80032AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='yiff.partypatreon', port=443): Max retries exceeded with url: /patreon_data/17913091/26402876/84059FEB-8E1A-4774-B16C-137F91797355.jpeg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000021C80032AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yiff_scraper.py", line 105, in <module>
    download_and_save_all(project)
  File "yiff_scraper.py", line 94, in download_and_save_all
    save_file(file_path)
  File "yiff_scraper.py", line 64, in save_file
    in_file = requests.get(URL, stream=True)
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mattl\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='yiff.partypatreon', port=443): Max retries exceeded with url: /patreon_data/17913091/26402876/84059FEB-8E1A-4774-B16C-137F91797355.jpeg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000021C80032AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

**Comment by ghost** [comment]
Have you noted the ` Max retries exceeded with url: /patreon_data/`* part?

For reference, I get the same error. I haven't run the tool before. Have you tried on multiple days?

During installation I receive these errors on Windows 10, haven't bothered to downgrade:

```
ERROR: lyricsgenius 0.9.5 has requirement beautifulsoup4==4.6.0, but you'll have beautifulsoup4 4.7.1 which is incompatible.
ERROR: lyricsgenius 0.9.5 has requirement requests==2.18.1, but you'll have requests 2.21.0 which is incompatible.
```

**Comment by ghost** [comment]
Here is my terminal output on Ubuntu:
```
*Starting project 7225754

Downloading 1.jpg
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/root/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/root/.local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/root/.local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f447fd3c8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='yiff.partypatreon', port=443): Max retries exceeded with url: /patreon_data/7225754/26575068/1.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f447fd3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yiff_scraper.py", line 105, in <module>
    download_and_save_all(project)
  File "yiff_scraper.py", line 94, in download_and_save_all
    save_file(file_path)
  File "yiff_scraper.py", line 64, in save_file
    in_file = requests.get(URL, stream=True)
  File "/root/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='yiff.partypatreon', port=443): Max retries exceeded with url: /patreon_data/7225754/26575068/1.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f447fd3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by ghost** [comment]
i found a fix!
simply remove the /patreon from the url
exemple: https://yiff.party/patreon/17913091 become https://yiff.party/17913091

**Comment by shubham418** [comment]
Hi @Mattlau04 , must have been some problem with previous code. But editing the url should not be necessary now.
